### ISSUE TITLE
isWalletLocked and lockStateChanged return incorrect values in Xperience Wallet

### ISSUE THREAD

**Issue by chilligerchief** [parallelchain-io/parallelchain-docs#19]
While building a DApp frontend, I noticed, that both the `isWalletLocked` Method and the `lockStateChanged` Event return the wrong values in the xperience browser extension.

The documentation states that they should return `true` if the wallet is locked, wich makes sense regarding the naming of the functions.
However, both return `true` if the wallet is unlocked, or is switching to an unlocked state in case of the event.

I think this should be fixed in the wallet, not in the documentation, but since there is no repository for the extension I don't know where to report this otherwise.

**Comment by chilligerchief** [comment]
@kayac-parallel-chain can you comment on the status of this issue? Or make the wallet extension open source, so I can contribute to that. This should be a matter of a few minutes to fix that.

**Comment by kayac-chang** [comment]
Hello @chilligerchief, thank you for reporting the issue. 
We are working on this issue currently. 
The fix has been done, but we are still waiting for review by the Chrome web store.

**Comment by chilligerchief** [comment]
Thanks for the notice. I will wait for the latest version.

**Comment by chilligerchief** [comment]
Looks like it is resolved in the currend version. Thank you.
